### PR TITLE
Don't add lines with just 4 spaces

### PR DESCRIPTION
**Pull request by jorrit**
When `TraitFile::generateMethods()` indents the method body by 4 lines it also indents empty lines, which is not necessary. This change removes those 4 trailing spaces.

I also added a commit that makes sure each file ends with an empty line.

### CODE REVIEW

**Comment by mghoneimy** [comment]
Love to see those changes!

Thank you for your continued contributions @jorrit !! :smiley:

**Comment by jorrit** [comment]
You're welcome!

**Comment by jorrit** [comment]
This change caused a problem because of something I did not expect. When I install a Composer dependency on Windows, the file has LF line endings. This means that when a method is generated by for instance `ObjectClassBuilder->addScalarSetter()` contains only LF's while in `TraitFile->generateMethods()` the replacements are done based on CRLF's.

This problem is more generic than that because on Windows the output files will have both CRLF's and LF's.

I haven't created a PR yet because I don't yet know the best way to fix this. Maybe normalize the line endings in `TraitFile->addMethod()`?

**Comment by jorrit** [comment]
The replacement patterns before this patch worked on `\n` but my change made it such that they work on `\r\n` on Windows. However, the method bodies are generated by inline string variables. Those variables have the line ending of whatever the line ending of the PHP file like `ObjectClassBuilder` happens to be.

My git clone of the source of this project uses CRLF and with that, it works. But when I use the composer package in my project, the source files created by composer have LF only, and then the method bodies have `\n` while the replacements looks for `CRLF`.

I think #17 fixes this. This change also makes sure the output files have consistent line endings, which I think is a plus.

**Pull request merged**
