### PR TITLE
Process deprecated fields

### PR DESCRIPTION
**Pull request by jorrit**
After this change deprecated fields will be converted to PHP code and a `@deprecated` comment will be added to these fields.

### CODE REVIEW

**Comment by mghoneimy** [comment]
@jorrit I apologize for having taken too long to look into this. I'm looking at the code now, meanwhile can you please check the failed build on jenkins, not sure why it's not showing up on the pull request, it normally does:
https://travis-ci.org/github/mghoneimy/php-graphql-oqm/jobs/706187242

Thanks!

**Comment by mghoneimy** [comment]
I took a look at the problems in travis and they don't seem to be related to your branch. Taking a look at them now.

**Comment by mghoneimy** [comment]
@jorrit I have 2 comments:
1. I found a problem on master related to tests. I fixed the problem and pushed master with a new tag `v1.0.5`, can you please rebase your pull request on master after this change? This should solve the failing tests problem.
2. While I have no comments on any of your changes, code looks neat and tidy, I feel like something is missing. None of the graphql queries in the package fetches the `isDeprecated` nor the `deprecationReason` attributes, and I don't see any changes your have made to that part in the `SchemaInspector` class. Can you explain to me how this actually works?
For instance, how did `isDeprecated` and `deprecationReason` keys get added to the `$fieldArray` array in the `SchemaClassGenerator` line 101? I don't see any changes in the `SchemaInspector` class that lead to their inclusion in the array. There must be something I'm missing here.

Thanks!

**Comment by jorrit** [comment]
You weren't missing anything, I forgot to change the actual queries themselves! Well spotted.

The changes have been rebased.

**Comment by mghoneimy** [comment]
@jorrit Things look good from my side. I just have a question before I merge this pull request, were you able to test the query on a live API example that has some deprecated attributes? If so, can you please provide me with a link to such an API server? If not, do you know a way that we can test this on a live API?
I just want to make a sanity check on the query to make sure that everything works well end-to-end. The live API's I typically do the end-to-end tests on don't have deprecated fields unfortunately.

**Comment by mghoneimy** [comment]
That's great! I tested the new feature with the Stanford API at https://hivdb.stanford.edu/graphql and it worked as expected! Merging now!

Thanks @jorrit for your contribution!

**Comment by jorrit** [comment]
You're welcome and thanks for maintaining this package.

**Pull request merged**
